// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.30.2
// source: src/proto/item.proto

package departament

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DepartamentService_ListPerson_FullMethodName = "/departament.departamentService/ListPerson"
)

// DepartamentServiceClient is the client API for DepartamentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DepartamentServiceClient interface {
	ListPerson(ctx context.Context, in *ListPersonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListPersonResponse], error)
}

type departamentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDepartamentServiceClient(cc grpc.ClientConnInterface) DepartamentServiceClient {
	return &departamentServiceClient{cc}
}

func (c *departamentServiceClient) ListPerson(ctx context.Context, in *ListPersonRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListPersonResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DepartamentService_ServiceDesc.Streams[0], DepartamentService_ListPerson_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListPersonRequest, ListPersonResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DepartamentService_ListPersonClient = grpc.ServerStreamingClient[ListPersonResponse]

// DepartamentServiceServer is the server API for DepartamentService service.
// All implementations must embed UnimplementedDepartamentServiceServer
// for forward compatibility.
type DepartamentServiceServer interface {
	ListPerson(*ListPersonRequest, grpc.ServerStreamingServer[ListPersonResponse]) error
	mustEmbedUnimplementedDepartamentServiceServer()
}

// UnimplementedDepartamentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDepartamentServiceServer struct{}

func (UnimplementedDepartamentServiceServer) ListPerson(*ListPersonRequest, grpc.ServerStreamingServer[ListPersonResponse]) error {
	return status.Error(codes.Unimplemented, "method ListPerson not implemented")
}
func (UnimplementedDepartamentServiceServer) mustEmbedUnimplementedDepartamentServiceServer() {}
func (UnimplementedDepartamentServiceServer) testEmbeddedByValue()                            {}

// UnsafeDepartamentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DepartamentServiceServer will
// result in compilation errors.
type UnsafeDepartamentServiceServer interface {
	mustEmbedUnimplementedDepartamentServiceServer()
}

func RegisterDepartamentServiceServer(s grpc.ServiceRegistrar, srv DepartamentServiceServer) {
	// If the following call panics, it indicates UnimplementedDepartamentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DepartamentService_ServiceDesc, srv)
}

func _DepartamentService_ListPerson_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPersonRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DepartamentServiceServer).ListPerson(m, &grpc.GenericServerStream[ListPersonRequest, ListPersonResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DepartamentService_ListPersonServer = grpc.ServerStreamingServer[ListPersonResponse]

// DepartamentService_ServiceDesc is the grpc.ServiceDesc for DepartamentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DepartamentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "departament.departamentService",
	HandlerType: (*DepartamentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListPerson",
			Handler:       _DepartamentService_ListPerson_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/proto/item.proto",
}
