// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: src/proto/shoppingcartservice.proto

package shoppingcart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=productId,proto3" json:"productId,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	PriceUnit     float64                `protobuf:"fixed64,3,opt,name=priceUnit,proto3" json:"priceUnit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProduct) Reset() {
	*x = AddProduct{}
	mi := &file_src_proto_shoppingcartservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProduct) ProtoMessage() {}

func (x *AddProduct) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shoppingcartservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProduct.ProtoReflect.Descriptor instead.
func (*AddProduct) Descriptor() ([]byte, []int) {
	return file_src_proto_shoppingcartservice_proto_rawDescGZIP(), []int{0}
}

func (x *AddProduct) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddProduct) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddProduct) GetPriceUnit() float64 {
	if x != nil {
		return x.PriceUnit
	}
	return 0
}

type ShoppingCartTotal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int32                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShoppingCartTotal) Reset() {
	*x = ShoppingCartTotal{}
	mi := &file_src_proto_shoppingcartservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingCartTotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingCartTotal) ProtoMessage() {}

func (x *ShoppingCartTotal) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_shoppingcartservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingCartTotal.ProtoReflect.Descriptor instead.
func (*ShoppingCartTotal) Descriptor() ([]byte, []int) {
	return file_src_proto_shoppingcartservice_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingCartTotal) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ShoppingCartTotal) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_src_proto_shoppingcartservice_proto protoreflect.FileDescriptor

const file_src_proto_shoppingcartservice_proto_rawDesc = "" +
	"\n" +
	"#src/proto/shoppingcartservice.proto\x12\fshoppingcart\"d\n" +
	"\n" +
	"AddProduct\x12\x1c\n" +
	"\tproductId\x18\x01 \x01(\x05R\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1c\n" +
	"\tpriceUnit\x18\x03 \x01(\x01R\tpriceUnit\"G\n" +
	"\x11ShoppingCartTotal\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount2_\n" +
	"\x13ShoppingCartService\x12H\n" +
	"\aaddItem\x12\x18.shoppingcart.AddProduct\x1a\x1f.shoppingcart.ShoppingCartTotal(\x010\x01B\x17Z\x15./src/pb/shoppingcartb\x06proto3"

var (
	file_src_proto_shoppingcartservice_proto_rawDescOnce sync.Once
	file_src_proto_shoppingcartservice_proto_rawDescData []byte
)

func file_src_proto_shoppingcartservice_proto_rawDescGZIP() []byte {
	file_src_proto_shoppingcartservice_proto_rawDescOnce.Do(func() {
		file_src_proto_shoppingcartservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_shoppingcartservice_proto_rawDesc), len(file_src_proto_shoppingcartservice_proto_rawDesc)))
	})
	return file_src_proto_shoppingcartservice_proto_rawDescData
}

var file_src_proto_shoppingcartservice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_proto_shoppingcartservice_proto_goTypes = []any{
	(*AddProduct)(nil),        // 0: shoppingcart.AddProduct
	(*ShoppingCartTotal)(nil), // 1: shoppingcart.ShoppingCartTotal
}
var file_src_proto_shoppingcartservice_proto_depIdxs = []int32{
	0, // 0: shoppingcart.ShoppingCartService.addItem:input_type -> shoppingcart.AddProduct
	1, // 1: shoppingcart.ShoppingCartService.addItem:output_type -> shoppingcart.ShoppingCartTotal
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_shoppingcartservice_proto_init() }
func file_src_proto_shoppingcartservice_proto_init() {
	if File_src_proto_shoppingcartservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_shoppingcartservice_proto_rawDesc), len(file_src_proto_shoppingcartservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_proto_shoppingcartservice_proto_goTypes,
		DependencyIndexes: file_src_proto_shoppingcartservice_proto_depIdxs,
		MessageInfos:      file_src_proto_shoppingcartservice_proto_msgTypes,
	}.Build()
	File_src_proto_shoppingcartservice_proto = out.File
	file_src_proto_shoppingcartservice_proto_goTypes = nil
	file_src_proto_shoppingcartservice_proto_depIdxs = nil
}
